{
 "title": "Geo-Mapping-ivan",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cities Top 10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(city) (failed_logins_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Countries Top 5",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(country) (failed_logins_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tried Usernames Top 15",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by(username) (failed_logins_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Where is Ivan hiding",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "failed_logins_total{}", "legendFormat": "__auto" },
    {}
   ]
  }
 ]
}